# Release as workerd binary
name: Release

on:
  push:
    branch: master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p dist
          npx esbuild --bundle --minify src/index.js > dist/worker.js
          npx workerd compile config.capnp > dist/hath-exporter-linux-amd64

      - id: generate-version
        name: Generate Release Version
        run: |
          echo "version=$(date --iso)" > "$GITHUB_OUTPUT"

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/hath-exporter-linux-amd64
          name: steps.generate-version.outputs.version
          prerelease: true
