# Release as workerd binary
name: Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir -p dist
          npx eslint build --bundle --minify src/index.js > dist/worker.js
          npx wrangler compile config.capnp > dist/hath-exporter

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: hath-exporter
          path: dist/hath-exporter
