# Release as workerd binary
name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p dist
          npx esbuild --bundle --minify src/index.js > dist/worker.js
          npx workerd compile config.capnp > dist/hath-exporter-linux-amd64

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/hath-exporter-linux-amd64
